// Generates the parts of Typst's standard library that are data, from the
// oracle (so build it first with `npm run oracle:build`):
//
//   src/generated/symbols.ts   every symbol in `sym`, from codex
//   src/generated/names.ts     the names in Typst's global scope, so Typlet can
//                              tell Typst names it doesn't support from unknown
//                              ones
//   test/fixtures/typst-<version>/names.jsonl
//                              every global and math name with its parameters,
//                              to check Typlet's built-in functions against
//
//   node tools/codegen/library.mjs

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { oracleVersion, runOracle } from '../lib/oracle.mjs';
import { writeJsonl } from '../lib/jsonl.mjs';

const root = join(import.meta.dirname, '../..');
const version = oracleVersion();

// --- symbols ---------------------------------------------------------------

// One line per symbol: its path (with the nested module, such as
// `gender.female`), then one field per variant, `modifiers=value`, all
// separated by tabs. Modifiers never contain `=`, so the first `=` splits.
const lines = new Map();
const variantDeprecations = [];
const bindingDeprecations = new Map();
for (const s of runOracle(['symbols'])) {
  const path = s.module ? `${s.module}.${s.name}` : s.name;
  if (/[\t\n]/.test(s.value)) throw new Error(`symbol ${path} contains a tab or newline`);
  if (!lines.has(path)) lines.set(path, [path]);
  lines.get(path).push(`${s.modifiers}=${s.value}`);
  if (s.deprecated) variantDeprecations.push([path, s.modifiers, s.deprecated]);
  if (s.bindingDeprecated) bindingDeprecations.set(path, s.bindingDeprecated);
}
const variants = [...lines.values()].reduce((sum, line) => sum + line.length - 1, 0);

writeFileSync(
  join(root, 'src/generated/symbols.ts'),
  `// Generated by tools/codegen/library.mjs from codex, the symbol crate of Typst
// ${version} (Apache-2.0). Do not edit by hand.
//
// ${lines.size} symbols with ${variants} variants, in codex's order. One line per symbol:
// its path, then \`modifiers=value\` for each variant, separated by tabs.

export const SYMBOLS =
  ${JSON.stringify([...lines.values()].map((line) => line.join('\t')).join('\n'))};

/** Deprecated variants: [symbol path, modifiers, message]. */
export const VARIANT_DEPRECATIONS: readonly (readonly [string, string, string])[] = ${JSON.stringify(variantDeprecations)};

/** Deprecated symbols: [symbol path, message]. */
export const BINDING_DEPRECATIONS: readonly (readonly [string, string])[] = ${JSON.stringify([...bindingDeprecations])};
`,
);
console.log(`symbols.ts: ${lines.size} symbols, ${variants} variants`);

// --- names -----------------------------------------------------------------

const names = runOracle(['names']);
const global = names.filter((n) => n.scope === 'global');
writeFileSync(
  join(root, 'src/generated/names.ts'),
  `// Generated by tools/codegen/library.mjs from Typst ${version}. Do not edit by hand.
//
// The ${global.length} names in Typst's global scope, as \`name:type\` separated by spaces.

export const GLOBAL_NAMES =
  ${JSON.stringify(global.map((n) => `${n.name}:${n.type}`).join(' '))};
`,
);
const fixtureDir = join(root, `test/fixtures/typst-${version}`);
mkdirSync(fixtureDir, { recursive: true });
writeJsonl(join(fixtureDir, 'names.jsonl'), names);
console.log(`names.ts: ${global.length} global names; names.jsonl: ${names.length} names`);
