// Generates src/generated/math-class.ts from the unicode-math-class crate, the
// table of Unicode math classes Typst uses (MathClass.txt, revision 15).
//
//   node tools/codegen/math-class.mjs
//
// The crate's sources come from the cargo registry, so build the oracle first.

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { cratePath } from '../lib/cargo.mjs';

// The variant order of `unicode_math_class::MathClass`.
const CLASSES = [
  'Normal', 'Alphabetic', 'Binary', 'Closing', 'Diacritic', 'Fence', 'GlyphPart', 'Large',
  'Opening', 'Punctuation', 'Relation', 'Space', 'Unary', 'Vary', 'Special',
];

const dir = cratePath('unicode-math-class');
const version = /unicode-math-class-([\d.]+)/.exec(dir)?.[1] ?? '?';
const source = readFileSync(join(dir, 'src/classes.rs'), 'utf8');

const entries = [...source.matchAll(/\('(\\u\{([0-9a-fA-F]+)\}|.)', (\w+)\)/gu)].map((m) => {
  const cp = m[2] !== undefined ? parseInt(m[2], 16) : m[1].codePointAt(0);
  const cls = CLASSES.indexOf(m[3]);
  if (cls < 0) throw new Error(`unknown class ${m[3]}`);
  return [cp, cls];
});
if (entries.length < 2000) throw new Error(`parsed only ${entries.length} entries`);

// Merge consecutive code points with the same class into runs. Each run is
// stored as three numbers: the gap since the previous run's end, the run's
// length, and the class.
const runs = [];
for (const [cp, cls] of entries) {
  const last = runs.at(-1);
  if (last && last.cls === cls && last.start + last.len === cp) last.len++;
  else runs.push({ start: cp, len: 1, cls });
}
const packed = [];
let end = 0;
for (const run of runs) {
  packed.push(run.start - end, run.len, run.cls);
  end = run.start + run.len;
}

const out = `// Generated by tools/codegen/math-class.mjs from unicode-math-class ${version}
// (MIT OR Apache-2.0, used under MIT). Do not edit by hand.
//
// Unicode math classes (MathClass.txt, revision 15) for ${entries.length} code points,
// packed as ${runs.length} runs of [gap since the previous run, length, class].

export const MATH_CLASS_NAMES = ${JSON.stringify(CLASSES)} as const;

export const MATH_CLASS_RUNS: readonly number[] = [${packed.join(',')}];
`;
writeFileSync(join(import.meta.dirname, '../../src/generated/math-class.ts'), out);
console.log(`math-class.ts: ${entries.length} code points in ${runs.length} runs`);
