// Generates src/generated/mathml.ts from typst-assets' MathML data, the
// operator dictionary of MathML Core that Typst's MathML export uses
// (files/mathml/data.rs, itself generated from the W3C tables).
//
//   node tools/codegen/mathml.mjs
//
// The crate's sources come from the cargo registry, so build the oracle first.

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { cratePath } from '../lib/cargo.mjs';

const dir = cratePath('typst-assets');
const version = /typst-assets-([\d.]+)/.exec(dir)?.[1] ?? '?';
const source = readFileSync(join(dir, 'files/mathml/data.rs'), 'utf8');

/** The body of a `const NAME: … = &[ … ];` table. */
function table(name) {
  const match = new RegExp(`const ${name}: [^=]+= &\\[([\\s\\S]*?)\\];`).exec(source);
  if (!match) throw new Error(`table ${name} not found`);
  return match[1];
}

const charOf = (literal) => {
  const m = /^'\\u\{([0-9A-Fa-f]+)\}'$/.exec(literal.trim());
  if (!m) throw new Error(`unexpected char literal ${literal}`);
  return parseInt(m[1], 16);
};

// Operator categories: form, lspace, rspace and property flags.
const PROPERTIES = { STRETCHY: 1, SYMMETRIC: 2, LARGEOP: 4, MOVABLELIMITS: 8 };
const categories = {};
for (const m of source.matchAll(/static CATEGORY_(\w+): OperatorInfo = OperatorInfo \{([\s\S]*?)\};/g)) {
  const body = m[2];
  const form = /form: (?:Some\(Form::(\w+)\)|None)/.exec(body)[1] ?? null;
  const lspace = Number(/lspace: ([\d.]+)/.exec(body)[1]);
  const rspace = Number(/rspace: ([\d.]+)/.exec(body)[1]);
  let flags = 0;
  for (const [name, bit] of Object.entries(PROPERTIES)) if (new RegExp(`Properties::${name}\\b`).test(body)) flags |= bit;
  categories[m[1]] = [form && form.toLowerCase(), lspace, rspace, flags];
}

// The category encodings used by OPERATOR_TABLE's high nibble.
const encodings = {};
for (const m of /fn from_encoding[\s\S]*?\{([\s\S]*?)\n\}/.exec(source)[1].matchAll(/0x([0-9a-f]+) => Category::(\w+)/g)) {
  encodings[parseInt(m[1], 16)] = m[2];
}

const operators = [...table('OPERATOR_TABLE').matchAll(/\(0x([0-9a-f]+), 0x([0-9a-f]+)\)/g)].flatMap((m) => [
  parseInt(m[1], 16),
  parseInt(m[2], 16),
]);
const twoAscii = [...table('TWO_ASCII_CHARS_TABLE').matchAll(/"((?:[^"\\]|\\.)*)"/g)].map((m) => JSON.parse(`"${m[1]}"`));
const fences = [...table('FENCE_TABLE').matchAll(/\('([^']+)', 0x([0-9a-f]+)\)/g)].flatMap((m) => [
  charOf(`'${m[1]}'`),
  parseInt(m[2], 16),
]);
const separators = table('SEPARATOR_TABLE').split(',').filter((s) => s.trim()).map(charOf);
const inlineAxis = [
  ...[...table('INLINE_AXIS_BMP_TABLE').matchAll(/0x([0-9a-f]+)/g)].map((m) => parseInt(m[1], 16)),
  ...table('INLINE_AXIS_NON_BMP_TABLE').split(',').filter((s) => s.trim()).map(charOf),
];

const out = `// Generated by tools/codegen/mathml.mjs from typst-assets ${version}, files/mathml/data.rs
// (Apache-2.0), derived from the MathML Core operator dictionary. Do not edit by hand.

/** Operator categories: [form, lspace, rspace, property flags]. Flags: 1 stretchy, 2 symmetric, 4 largeop, 8 movablelimits. */
export const CATEGORIES: Readonly<Record<string, readonly [string | null, number, number, number]>> = ${JSON.stringify(categories)};

/** The categories of OPERATOR_TABLE's encodings. */
export const ENCODINGS: Readonly<Record<number, string>> = ${JSON.stringify(encodings)};

/** Pairs of [key, data]: the key of a range's first entry; data's low nibble is the range length minus one, its high nibble the category encoding. */
export const OPERATOR_TABLE: readonly number[] = [${operators.join(',')}];

/** Operators of two ASCII characters, which map to U+0320 and up. */
export const TWO_ASCII_CHARS: readonly string[] = ${JSON.stringify(twoAscii)};

/** Pairs of [first character, length] of fence ranges. */
export const FENCE_TABLE: readonly number[] = [${fences.join(',')}];

export const SEPARATORS: readonly number[] = [${separators.join(',')}];

/** Operators that stretch along the inline axis. */
export const INLINE_AXIS: readonly number[] = [${inlineAxis.join(',')}];
`;
writeFileSync(join(import.meta.dirname, '../../src/generated/mathml.ts'), out);
console.log(
  `mathml.ts: ${Object.keys(categories).length} categories, ${operators.length / 2} operator ranges, ${fences.length / 2} fence ranges`,
);
